apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: cart
  envs:
    - cart/cart.env
- name: booking
  envs:
    - booking/booking.env

generatorOptions:
  disableNameSuffixHash: true